%ifndef STEPPINRAZOR_OPCODE_TABLE_H
%define STEPPINRAZOR_OPCODE_TABLE_H

opcodes:
	dq run_method.loop
	dq opcode_impl.aconst_null
	dq opcode_impl.iconst_m1
	dq opcode_impl.iconst_0
	dq opcode_impl.iconst_1
	dq opcode_impl.iconst_2
	dq opcode_impl.iconst_3
	dq opcode_impl.iconst_4
	dq opcode_impl.iconst_5
	dq opcode_impl.lconst_0
	dq opcode_impl.lconst_1
	dq opcode_impl.fconst_0
	dq opcode_impl.fconst_1
	dq opcode_impl.fconst_2
	dq opcode_impl.dconst_0
	dq opcode_impl.dconst_1
	dq opcode_impl.bipush
	dq opcode_impl.sipush
	dq opcode_impl.ldc
	dq opcode_impl.ldc_w
	dq opcode_impl.ldc2_w
	dq opcode_impl.load
	dq opcode_impl.wload
	dq opcode_impl.load
	dq opcode_impl.wload
	dq opcode_impl.load
	dq opcode_impl.load_0
	dq opcode_impl.load_1
	dq opcode_impl.load_2
	dq opcode_impl.load_3
	dq opcode_impl.wload_0
	dq opcode_impl.wload_1
	dq opcode_impl.wload_2
	dq opcode_impl.wload_3
	dq opcode_impl.load_0
	dq opcode_impl.load_1
	dq opcode_impl.load_2
	dq opcode_impl.load_3
	dq opcode_impl.wload_0
	dq opcode_impl.wload_1
	dq opcode_impl.wload_2
	dq opcode_impl.wload_3
	dq opcode_impl.load_0
	dq opcode_impl.load_1
	dq opcode_impl.load_2
	dq opcode_impl.load_3
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq opcode_impl.store
	dq opcode_impl.wstore
	dq opcode_impl.store
	dq opcode_impl.wstore
	dq opcode_impl.store
	dq opcode_impl.store_0
	dq opcode_impl.store_1
	dq opcode_impl.store_2
	dq opcode_impl.store_3
	dq opcode_impl.wstore_0
	dq opcode_impl.wstore_1
	dq opcode_impl.wstore_2
	dq opcode_impl.wstore_3
	dq opcode_impl.store_0
	dq opcode_impl.store_1
	dq opcode_impl.store_2
	dq opcode_impl.store_3
	dq opcode_impl.wstore_0
	dq opcode_impl.wstore_1
	dq opcode_impl.wstore_2
	dq opcode_impl.wstore_3
	dq opcode_impl.store_0
	dq opcode_impl.store_1
	dq opcode_impl.store_2
	dq opcode_impl.store_3
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq opcode_impl.pop
	dq opcode_impl.pop2
	dq opcode_impl.dup
	dq opcode_impl.dup_x1
	dq opcode_impl.dup_x2
	dq opcode_impl.dup2
	dq opcode_impl.dup2_x1
	dq opcode_impl.dup2_x2
	dq opcode_impl.swap
	dq opcode_impl.iadd
	dq opcode_impl.ladd
	dq opcode_impl.fadd
	dq opcode_impl.dadd
	dq opcode_impl.isub
	dq opcode_impl.lsub
	dq opcode_impl.fsub
	dq opcode_impl.dsub
	dq opcode_impl.imul
	dq opcode_impl.lmul
	dq opcode_impl.fmul
	dq opcode_impl.dmul
	dq opcode_impl.idiv
	dq opcode_impl.ldiv
	dq opcode_impl.fdiv
	dq opcode_impl.ddiv
	dq opcode_impl.irem
	dq opcode_impl.lrem
	dq opcode_impl.frem
	dq opcode_impl.drem
	dq opcode_impl.ineg
	dq opcode_impl.lneg
	dq opcode_impl.fneg
	dq opcode_impl.dneg
	dq opcode_impl.ishl
	dq opcode_impl.lshl
	dq opcode_impl.ishr
	dq opcode_impl.lshr
	dq opcode_impl.iushr
	dq opcode_impl.lushr
	dq opcode_impl.iand
	dq opcode_impl.land
	dq opcode_impl.ior
	dq opcode_impl.lor
	dq opcode_impl.ixor
	dq opcode_impl.lxor
	dq opcode_impl.iinc
	dq opcode_impl.i2l
	dq opcode_impl.i2f
	dq opcode_impl.i2d
	dq opcode_impl.l2i
	dq opcode_impl.l2f
	dq opcode_impl.l2d
	dq opcode_impl.f2i
	dq opcode_impl.f2l
	dq opcode_impl.f2d
	dq opcode_impl.d2i
	dq opcode_impl.d2l
	dq opcode_impl.d2f
	dq opcode_impl.i2b
	dq opcode_impl.i2c
	dq opcode_impl.i2s
	dq opcode_impl.lcmp
	dq opcode_impl.fcmpl
	dq opcode_impl.fcmpg
	dq opcode_impl.dcmpl
	dq opcode_impl.dcmpg
	dq opcode_impl.ifeq
	dq opcode_impl.ifne
	dq opcode_impl.iflt
	dq opcode_impl.ifge
	dq opcode_impl.ifgt
	dq opcode_impl.ifle
	dq opcode_impl.if_icmpeq
	dq opcode_impl.if_icmpne
	dq opcode_impl.if_icmplt
	dq opcode_impl.if_icmpge
	dq opcode_impl.if_icmpgt
	dq opcode_impl.if_icmple
	dq opcode_impl.if_acmpeq
	dq opcode_impl.if_acmpne
	dq opcode_impl.goto
	dq opcode_impl.jsr
	dq opcode_impl.ret
	dq opcode_impl.tableswitch
	dq opcode_impl.lookupswitch
	dq opcode_impl.ireturn
	dq opcode_impl.lreturn
	dq opcode_impl.freturn
	dq opcode_impl.dreturn
	dq opcode_impl.areturn
	dq opcode_impl.return
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq opcode_impl.ifnull
	dq opcode_impl.ifnonnull
	dq opcode_impl.goto_w
	dq opcode_impl.jsr_w
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.loop
	dq run_method.end

%endif
